<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Notifications\SendOtpNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Log;
use Inertia\Inertia;

/**
 * TwoFactorAuthController
 * 
 * Handles two-factor authentication (2FA) OTP verification during the login process.
 * When a user with 2FA enabled attempts to log in, they are temporarily logged out
 * and required to verify their identity with a one-time password sent to their email.
 * 
 * 2FA Login Flow:
 * 1. User enters email and password (AuthenticatedSessionController)
 * 2. System validates credentials
 * 3. System checks if user has 2FA enabled
 * 4. If 2FA enabled:
 *    a. Generate and send OTP to user's email
 *    b. Temporarily logout user
 *    c. Store email in session
 *    d. Redirect to 2FA challenge page (show method)
 * 5. User enters 6-digit OTP code (verify method)
 * 6. System validates OTP
 * 7. If valid: clear OTP, login user, redirect to home
 * 8. If invalid: show error, allow resend
 * 
 * Security Features:
 * - OTP generated by User model (stored in database)
 * - OTP has expiration time (typically 10 minutes)
 * - Rate limiting on resend (1 per minute per IP)
 * - Session-based email storage
 * - User temporarily logged out until 2FA verification
 * - OTP cleared immediately after successful verification
 * 
 * Session Data:
 * - '2fa_email': User's email address for OTP verification
 * 
 * @package App\Http\Controllers\Auth
 * 
 * @see \App\Http\Controllers\Auth\AuthenticatedSessionController
 * @see \App\Models\User::generateOtp()
 * @see \App\Models\User::verifyOtp()
 * @see \App\Models\User::clearOtp()
 */
class TwoFactorAuthController extends Controller
{
    /**
     * Show the 2FA challenge page.
     * 
     * Displays the two-factor authentication verification form where users
     * enter the 6-digit OTP code sent to their email. If no email is stored
     * in the session (indicating an expired or invalid 2FA attempt), the user
     * is redirected back to the login page.
     * 
     * Page Features:
     * - 6-digit OTP input field
     * - Resend OTP button
     * - Email address display (masked or full)
     * - Session status messages
     * 
     * @return \Illuminate\Http\RedirectResponse|\Inertia\Response
     *         Redirects to login if session expired,
     *         otherwise renders 2FA challenge page
     * 
     * Session Requirements:
     * - '2fa_email': Must contain user's email address
     * 
     * Props Passed to Frontend:
     * - status (string|null): Session status messages (e.g., OTP resent)
     * 
     * Session Expiration Handling:
     * - If session lost: user must restart login process
     * - Prevents unauthorized access to 2FA page
     * 
     * @see resources/js/Pages/Auth/TwoFactorChallenge.vue
     */
    public function show()
    {
        // Check if 2FA email exists in session
        // This was set during login process in AuthenticatedSessionController
        if (!session('2fa_email')) {
            // No session data - redirect to login page
            // User must restart the login process
            return redirect()->route('login');
        }

        // Render the 2FA challenge page with status messages
        return Inertia::render('Auth/TwoFactorChallenge', [
            'status' => session('status'),
        ]);
    }

    /**
     * Verify the 2FA OTP code.
     * 
     * Validates the user-submitted OTP code against the stored OTP in the database.
     * If valid, clears the OTP, logs the user in, and redirects to the home page.
     * 
     * Verification Process:
     * 1. Validate OTP format (6 characters)
     * 2. Retrieve email from session
     * 3. Find user by email
     * 4. Verify OTP is valid and not expired
     * 5. Clear OTP from database
     * 6. Log user in
     * 7. Clear 2FA session data
     * 8. Redirect to home page
     * 
     * @param Request $request The HTTP request containing OTP code
     * 
     * @return \Illuminate\Http\RedirectResponse Redirects to home on success,
     *                                           back to form with errors on failure
     * 
     * Request Data Expected:
     * - otp (string): 6-character OTP code
     * 
     * Validation Rules:
     * - otp: 'required|string|size:6'
     * 
     * Error Scenarios:
     * 1. Session expired: "Session expired. Please login again."
     * 2. User not found: "User not found."
     * 3. Invalid/expired OTP: "Invalid or expired OTP code."
     * 
     * Database Operations:
     * - Queries users table by email
     * - Verifies OTP against stored value and expiration
     * - Clears OTP fields after successful verification
     * 
     * Session Operations:
     * - Retrieves '2fa_email'
     * - Clears '2fa_email' after successful login
     * - Sets 'status' flash message for welcome notification
     * 
     * Authentication:
     * - Uses Auth::login() to authenticate user
     * - User is fully logged in after successful verification
     * 
     * @see \App\Models\User::verifyOtp()
     * @see \App\Models\User::clearOtp()
     */
    public function verify(Request $request)
    {
        // Validate OTP format
        // Must be exactly 6 characters (typically digits)
        $request->validate([
            'otp' => 'required|string|size:6',
        ]);

        // Retrieve user's email from session
        // This was stored during the login process
        $email = session('2fa_email');

        // Check if session still contains email
        if (!$email) {
            return back()->withErrors(['otp' => 'Session expired. Please login again.']);
        }

        // Find user by email address
        $user = User::where('email', $email)->first();

        // Verify user exists in database
        if (!$user) {
            return back()->withErrors(['otp' => 'User not found.']);
        }

        // Verify the OTP code is valid and not expired
        // verifyOtp() method checks against stored OTP and expiration time
        if (!$user->verifyOtp($request->otp)) {
            return back()->withErrors(['otp' => 'Invalid or expired OTP code.']);
        }

        // OTP is valid - clear it from database
        // Ensures one-time use and prevents OTP reuse
        $user->clearOtp();

        // Log the user in (complete the authentication)
        // User now has full access to authenticated routes
        Auth::login($user);

        // Clear 2FA email from session
        // Clean up after successful authentication
        session()->forget('2fa_email');

        // Redirect to home page with success message
        // Using '/' instead of route name for explicit home redirect
        return redirect('/')->with('status', 'Two-factor authentication successful!');
    }

    /**
     * Resend 2FA OTP.
     * 
     * Generates a new OTP and sends it via email. This endpoint is rate-limited
     * to prevent abuse, allowing only 1 resend request per minute per IP address.
     * 
     * Rate Limiting:
     * - 1 request per minute per IP address
     * - Uses Laravel's RateLimiter facade
     * - Returns back with status message when limit exceeded
     * - Includes seconds to wait in message
     * 
     * Process Flow:
     * 1. Check rate limit (1 per minute)
     * 2. Verify session data exists
     * 3. Find user by email
     * 4. Generate new OTP via User model
     * 5. Send OTP via email notification
     * 6. Set rate limiter for 60 seconds
     * 7. Return with success message
     * 
     * @param Request $request The HTTP request (typically form submission)
     * 
     * @return \Illuminate\Http\RedirectResponse Redirects back with status or error
     * 
     * Response Messages:
     * - Success: "New verification code sent!"
     * - Rate limited: "Please wait {seconds} seconds before requesting another code."
     * - Session expired: "Session expired. Please login again."
     * - User not found: "User not found."
     * - Email failed: "Failed to send verification code."
     * 
     * Rate Limiting Key:
     * - Format: 'resend-2fa-otp:{ip_address}'
     * - Duration: 60 seconds per attempt
     * 
     * Error Handling:
     * - Email sending exceptions are caught and logged
     * - User-friendly error message shown on failure
     * - Detailed error logged for debugging
     * 
     * Security Considerations:
     * - Rate limiting prevents spam/abuse
     * - IP-based limiting allows different users to resend independently
     * - New OTP invalidates previous OTP
     * - Session validation prevents unauthorized resends
     * 
     * @see \App\Models\User::generateOtp()
     * @see \App\Notifications\SendOtpNotification
     * @see \Illuminate\Support\Facades\RateLimiter
     */
    public function resend(Request $request)
    {
        // Create unique rate limiting key based on IP address
        // This allows different users to resend independently
        $key = 'resend-2fa-otp:' . $request->ip();

        // Check if rate limit has been exceeded (1 attempt allowed)
        if (RateLimiter::tooManyAttempts($key, 1)) {
            // Get remaining seconds until next attempt is allowed
            $seconds = RateLimiter::availableIn($key);

            // Return with countdown message
            return back()->with('status', "Please wait {$seconds} seconds before requesting another code.");
        }

        // Determine target user:
        // - During login challenge: use session('2fa_email')
        // - From authenticated profile page: use currently authenticated user
        $email = session('2fa_email');
        $user = null;
        if ($email) {
            $user = User::where('email', $email)->first();
        } else if (Auth::check()) {
            $user = $request->user();
        }

        // Verify user exists in database
        if (!$user) {
            return back()->withErrors(['otp' => 'User not found.']);
        }

        // Generate a new OTP code
        // This invalidates any previous OTP for security
        $otpCode = $user->generateOtp();

        // Send the new OTP via email notification
        try {
            $user->notify(new SendOtpNotification($otpCode));
        } catch (\Exception $e) {
            // Log error details for debugging
            Log::error('Failed to resend 2FA OTP: ' . $e->getMessage());

            // Return user-friendly error message
            return back()->withErrors(['otp' => 'Failed to send verification code.']);
        }

        // Record this resend attempt in rate limiter
        // Blocks further attempts for 60 seconds
        RateLimiter::hit($key, 60);

        // Return with success message
        return back()->with('status', 'New verification code sent!');
    }
}
