<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Add OTP and Two-Factor Authentication Fields Migration
 * 
 * Adds columns to support OTP verification and two-factor authentication:
 * - OTP code and expiration for email verification
 * - User verification status flag
 * - Two-factor authentication settings
 * 
 * Purpose:
 * Enhances security by adding email verification via OTP and optional 2FA.
 * Users must verify their email with a 6-digit code before accessing the app.
 * 
 * Created: December 17, 2025
 * 
 * @see \App\Models\User
 * @see \App\Notifications\SendOtpNotification
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     * 
     * Adds six new columns to the users table for OTP and 2FA functionality.
     */
    public function up(): void
    {
        Schema::table('users', function (Blueprint $table) {
            /**
             * OTP Code Column
             * 
             * Type: string (nullable)
             * Stores: 6-digit OTP code (e.g., "123456")
             * 
             * Purpose:
             * - Email verification during registration
             * - Password reset verification
             * - Two-factor authentication challenges
             * 
             * Generated by: User::generateOtp()
             * Verified by: User::verifyOtp()
             * Cleared by: User::clearOtp()
             * 
             * Lifecycle:
             * 1. User registers or requests OTP
             * 2. Random 6-digit code generated
             * 3. Stored in this column
             * 4. Sent via email
             * 5. User enters code
             * 6. Code verified and cleared
             * 
             * Security:
             * - Should be cleared immediately after verification
             * - Works with otp_expires_at for time-based expiration
             * - Single-use only
             */
            $table->string('otp_code')->nullable();

            /**
             * OTP Expiration Column
             * 
             * Type: timestamp (nullable)
             * Stores: When the OTP code expires
             * 
             * Default Expiration: 10 minutes from generation
             * 
             * Purpose:
             * Limits the validity period of OTP codes to prevent:
             * - Old codes being reused
             * - Extended brute force windows
             * - Security vulnerabilities
             * 
             * Usage:
             * - Set by User::generateOtp() to now + 10 minutes
             * - Checked by User::verifyOtp() using isFuture()
             * - Cleared by User::clearOtp() after verification
             * 
             * Example Flow:
             * Generated: 2025-12-20 00:00:00
             * Expires: 2025-12-20 00:10:00
             * If user tries at 00:15:00 -> rejected (expired)
             */
            $table->timestamp('otp_expires_at')->nullable();

            /**
             * Is Verified Column
             * 
             * Type: boolean
             * Default: false
             * 
             * Purpose:
             * Tracks whether user has completed OTP verification.
             * Different from email_verified_at (Laravel's built-in verification).
             * 
             * States:
             * - false: User registered but hasn't verified OTP
             * - true: User verified OTP and can access application
             * 
             * Middleware Protection:
             * Used by EnsureOtpVerified middleware to restrict access:
             * ```
             * Route::middleware(['auth', 'otp.verified'])->group(function () {
             *     // Protected routes requiring OTP verification
             * });
             * ```
             * 
             * Set to true:
             * - After successful OTP verification
             * - In OtpVerificationController@verify
             * 
             * Use Cases:
             * - Prevent unverified users from accessing app
             * - Ensure email ownership
             * - Additional security layer beyond password
             */
            $table->boolean('is_verified')->default(false);

            /**
             * Two-Factor Enabled Column
             * 
             * Type: boolean
             * Default: false
             * 
             * Purpose:
             * Indicates if user has enabled two-factor authentication.
             * 
             * States:
             * - false: 2FA disabled (standard password login only)
             * - true: 2FA enabled (requires second factor)
             * 
             * Enable Process:
             * 1. User navigates to security settings
             * 2. Enables 2FA option
             * 3. Secret generated and stored
             * 4. User confirms setup
             * 5. This flag set to true
             * 6. two_factor_confirmed_at timestamp set
             * 
             * Login Flow (when true):
             * 1. User enters email/password
             * 2. Credentials validated
             * 3. OTP generated and sent
             * 4. User enters OTP
             * 5. OTP verified
             * 6. User authenticated
             * 
             * Check in Code:
             * ```
             * if ($user->two_factor_enabled) {
             *     // Generate and send OTP for 2FA
             * }
             * ```
             */
            $table->boolean('two_factor_enabled')->default(false);

            /**
             * Two-Factor Secret Column
             * 
             * Type: string (nullable)
             * 
             * Purpose:
             * Stores secret key for TOTP (Time-based One-Time Password) generation.
             * Used if implementing authenticator app-based 2FA (Google Authenticator, etc.).
             * 
             * Format:
             * Base32-encoded string (e.g., "JBSWY3DPEHPK3PXP")
             * 
             * Usage:
             * - Generated when user enables 2FA
             * - Shared with authenticator app via QR code
             * - Used to verify TOTP codes during login
             * - Remains constant until 2FA is disabled
             * 
             * Security:
             * - Hidden from serialization (in User model)
             * - Never exposed in API responses
             * - Should be encrypted at rest
             * - Unique per user
             * 
             * TOTP Algorithm:
             * - Uses secret + current time
             * - Generates 6-digit code
             * - Valid for 30-second window
             * - Synchronized with authenticator app
             * 
             * Alternative Approach:
             * If using email/SMS OTP instead of TOTP, this column may be null.
             * Current implementation uses email OTP (otp_code column).
             */
            $table->string('two_factor_secret')->nullable();

            /**
             * Two-Factor Confirmed At Column
             * 
             * Type: timestamp (nullable)
             * 
             * Purpose:
             * Tracks when user successfully completed 2FA setup.
             * Prevents incomplete 2FA setups from being enforced.
             * 
             * Setup Flow:
             * 1. User enables 2FA (two_factor_enabled = true)
             * 2. Secret generated
             * 3. User scans QR code
             * 4. User enters test code to confirm
             * 5. Code verified
             * 6. This timestamp set (confirms setup complete)
             * 
             * Verification Check:
             * Both conditions must be true to enforce 2FA:
             * ```
             * public function hasEnabledTwoFactorAuthentication(): bool
             * {
             *     return $this->two_factor_enabled && 
             *            $this->two_factor_confirmed_at !== null;
             * }
             * ```
             * 
             * Why Confirmation Needed:
             * - Prevents users from being locked out
             * - Ensures setup was completed successfully
             * - Allows rollback if setup fails
             * 
             * Benefits:
             * - User can enable 2FA without immediate enforcement
             * - Setup can be tested before activation
             * - Prevents accidental lockouts
             * 
             * Set When:
             * - User successfully verifies first 2FA code
             * - After QR code scanning and testing
             * - In TwoFactorAuthController@confirmSetup
             * 
             * Cleared When:
             * - User disables 2FA
             * - Admin resets user's 2FA
             * - Security breach requires reset
             */
            $table->timestamp('two_factor_confirmed_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     * 
     * Removes all OTP and 2FA columns from users table.
     * 
     * Warning:
     * Rolling back this migration will:
     * - Delete all OTP codes
     * - Remove 2FA settings for all users
     * - Reset verification status
     * - This data cannot be recovered
     * 
     * Consider:
     * - Backing up data before rollback
     * - Notifying users if 2FA will be disabled
     * - Having migration plan for affected users
     */
    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn([
                'otp_code',
                'otp_expires_at',
                'is_verified',
                'two_factor_enabled',
                'two_factor_secret',
                'two_factor_confirmed_at'
            ]);
        });
    }
};
